### ISSUE TITLE
not Stata format

### ISSUE THREAD

**Issue by pupble** [ShutterZor/Commonly-Used-Control-Variables#1]
![image](https://github.com/ShutterZor/Commonly-Used-Control-Variables/assets/128626823/65d7ce26-5247-4ab0-9bcb-ac53bd549190)

**Comment by pupble** [comment]
不用了，谢谢。我把整个包下载下来了是可以的

**Comment by ShutterZor** [comment]
你好，这个原因我也不太清楚，我使用Gitee调用数据也有概率出现这个问题。在网络“通畅”的情况下，我建议优先考虑使用GitHub调用
